import { ArrowRight, Facebook, MessageCircle, Phone } from 'lucide-react'
import Link from 'next/link'

import { FACEBOOK_URL, LOGO_URL, PHONE_DISPLAY, PHONE_VALUE, ZALO_URL } from '@/lib/site'

export function SiteFooter() {
  return <>
    <section className="bg-brand text-white"><div className="section-shell flex flex-col gap-7 py-12 sm:py-16 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-3xl"><p className="text-sm font-bold text-orange-100">Đội bóng đã có ý tưởng?</p><h2 className="mt-3 font-display text-4xl font-bold leading-[.95] sm:text-6xl">Gửi logo, màu sắc và số lượng. Chúng tôi cùng bạn hoàn thiện mẫu áo.</h2></div><a className="inline-flex min-h-13 items-center gap-2 self-start rounded-lg bg-white px-6 text-sm font-black text-brand" href={ZALO_URL} target="_blank">Nhận tư vấn <ArrowRight size={18} /></a></div></section>
    <footer className="bg-[#0b1220] pb-24 text-slate-300 lg:pb-0"><div className="section-shell grid gap-10 py-12 sm:py-16 md:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr]"><div><img alt="May Áo Bóng Đá" className="h-[43px] w-auto max-w-full" height="58" src={LOGO_URL} width="372" /><p className="mt-5 max-w-md text-sm leading-7 text-slate-400">Thiết kế và may áo bóng đá theo yêu cầu cho đội bóng, câu lạc bộ, công ty và giải phong trào.</p></div><div><h3 className="mb-4 text-sm font-black uppercase tracking-wider text-white">Khám phá</h3><nav className="grid gap-3 text-sm"><Link href="/shop/">Toàn bộ sản phẩm</Link><Link href="/ao-thiet-ke/">Áo thiết kế</Link><Link href="/ao-khong-logo/">Áo không logo</Link><Link href="/blog/">Tin tức áo bóng đá</Link></nav></div><div><h3 className="mb-4 text-sm font-black uppercase tracking-wider text-white">Liên hệ</h3><div className="grid gap-3 text-sm"><a className="inline-flex items-center gap-2" href={`tel:${PHONE_VALUE}`}><Phone size={16} /> {PHONE_DISPLAY}</a><a className="inline-flex items-center gap-2" href={ZALO_URL} target="_blank"><MessageCircle size={16} /> Zalo tư vấn</a><a className="inline-flex items-center gap-2" href={FACEBOOK_URL} target="_blank"><Facebook size={16} /> Facebook</a></div></div></div><div className="border-t border-white/10 py-5 text-center text-xs text-slate-500">© {new Date().getFullYear()} MayAoBongDa.vn · X24 Sport</div></footer>
    <div className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-2 border-t bg-white p-2 lg:hidden"><a className="inline-flex min-h-12 items-center justify-center gap-2 rounded-l-lg bg-[#0b1220] text-sm font-black text-white" href={`tel:${PHONE_VALUE}`}><Phone size={17} /> Gọi ngay</a><a className="inline-flex min-h-12 items-center justify-center gap-2 rounded-r-lg bg-brand text-sm font-black text-white" href={ZALO_URL} target="_blank"><MessageCircle size={17} /> Tư vấn mẫu</a></div>
  </>
}
