server {
    server_name pndsport.vn www.pndsport.vn;
    client_max_body_size 32M;
    access_log /var/log/nginx/pndsport.vn_access.log;
    error_log /var/log/nginx/pndsport.vn_error.log;
    if ($http_x_forwarded_proto = http) {
        return 301 https://$host$request_uri;
    }
    location / {
        proxy_pass http://10.10.0.58:3010;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/pndsport.vn/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pndsport.vn/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name pndsport.vn www.pndsport.vn;
    return 301 https://$host$request_uri;
}
