server {
    listen 80;
    listen [::]:80;
    server_name wp.mayaobongro.vn;

    root /var/www/wp.mayaobongro.vn;

    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
