import type { Metadata } from 'next'
import { ArrowRight, MessageCircle, Phone } from 'lucide-react'

import { Breadcrumbs, ProductGrid, SectionHeading } from '../../components'
import { formatPrice, previewBase, products } from '../../data'
import styles from '../../pnd.module.css'

export const metadata: Metadata = { title: 'Áo bóng đá PND Velocity 01', description: 'Mẫu áo bóng đá PND Velocity 01, giá từ 129.000đ.' }

export default function ProductDetailPage({ base = previewBase }: { base?: string } = {}) {
  const product = products[0]
  return <><Breadcrumbs base={base} items={[{ label: 'Bóng đá', href: `${base}/danh-muc/bong-da` }, { label: product.name }]} /><article className={styles.productDetail}><h1>{product.name}</h1><div className={styles.productLayout}><div className={styles.gallery}><div className={styles.thumbs}>{[1,2,3,4].map((item) => <button key={item} aria-label={`Xem ảnh ${item}`}>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={products[item - 1].image} alt="" /></button>)}</div><div className={styles.mainImage}>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={product.image} alt={product.name} /></div></div><section className={styles.productInfo}><div className={styles.productCode}><span>Mã: {product.code}</span><span>Danh mục: {product.category}</span></div><div className={styles.productPrice}><small>Giá thấp nhất</small><strong>{formatPrice(product.price)}</strong></div><p>Mẫu tham khảo dành cho đội bóng muốn phát triển phối màu và nhận diện riêng. Giá cuối cùng được xác nhận theo số lượng và cấu hình thực tế.</p><div className={styles.option}><span>Phối màu tham khảo</span><div className={styles.swatches}><button>Cam / Đen</button><button>Xanh / Trắng</button><button>Yêu cầu riêng</button></div></div><div className={styles.option}><span>Kiểu đặt áo</span><div className={styles.swatches}><button>Áo đội</button><button>CLB</button><button>Doanh nghiệp</button></div></div><div className={styles.productCta}><a href="https://zalo.me/0989353247" target="_blank" rel="noreferrer"><MessageCircle size={17} /> Gửi yêu cầu thiết kế</a><a href="tel:0989353247"><Phone size={17} /> Gọi báo giá</a></div><div className={styles.detailFacts}><div><small>Giá hiển thị</small><b>Mức thấp nhất</b></div><div><small>Tùy chỉnh</small><b>Màu, logo, tên số</b></div><div><small>Xác nhận</small><b>Trước sản xuất</b></div></div></section></div><section className={styles.contentTabs}><div><h2>Thông tin sản phẩm</h2><p>PND Velocity 01 là phương án hình ảnh khởi đầu để đội trao đổi về bố cục và màu sắc. Khi gửi yêu cầu, khách hàng có thể đính kèm logo, danh sách tên số và mẫu tham khảo.</p><h3>Thông tin nên chuẩn bị</h3><ul><li>Số lượng dự kiến và nhóm người mặc.</li><li>Màu chủ đạo, màu phụ hoặc màu nhận diện hiện có.</li><li>Logo và nội dung cần xuất hiện trên áo.</li><li>Mốc thời gian dự kiến cần nhận sản phẩm.</li></ul></div><div><h2>Thông số mẫu</h2><div className={styles.specTable}><div><span>Mã mẫu</span><b>{product.code}</b></div><div><span>Môn thể thao</span><b>Bóng đá</b></div><div><span>Dạng sản phẩm</span><b>Áo đội nhóm</b></div><div><span>Màu hiển thị</span><b>{product.tone}</b></div><div><span>Trạng thái</span><b>Mẫu tham khảo</b></div></div></div></section><section className={styles.section}><div className={styles.sectionInner}><SectionHeading eyebrow="Gợi ý tiếp theo" title="Sản phẩm liên quan" href={`${base}/danh-muc/bong-da`} /><ProductGrid items={products.slice(1,5)} base={base} /></div></section></article></>
}
