export type BasketballAudience = {
  slug: string
  path: string
  eyebrow: string
  title: string
  shortTitle: string
  description: string
  heroTitle: string
  heroDescription: string
  heroImage?: string
  heroImageAlt?: string
  metaTitle: string
  metaDescription: string
  primaryCta: string
  secondaryCta: string
  proof: string[]
  pain: string
  outcome: string
  useCases: string[]
  benefits: { title: string; text: string }[]
  checklist: string[]
  steps: { title: string; text: string }[]
  faq: { question: string; answer: string }[]
}

export const BASKETBALL_AUDIENCES = [
  {
    slug: 'lop-truong-hoc',
    path: '/ao-bong-ro-lop-truong-hoc/',
    eyebrow: 'Lớp & Trường học',
    title: 'May áo bóng rổ cho lớp, trường học và đội tuyển sinh viên',
    shortTitle: 'Lớp & Trường học',
    description: 'Dành cho lớp học, đội tuyển trường, khoa, sinh viên và các giải nội bộ.',
    heroTitle: 'Đồng phục bóng rổ để cả lớp mặc đẹp, dễ chia size và kịp ngày thi đấu.',
    heroDescription: 'Từ áo lớp, đội khoa đến giải nội bộ, đội bạn có thể bắt đầu bằng màu trường, logo lớp hoặc mẫu áo yêu thích rồi duyệt maket trước khi may.',
    metaTitle: 'May Áo Bóng Rổ Cho Lớp & Trường Học',
    metaDescription: 'Landing page may áo bóng rổ cho lớp học, trường học, khoa, sinh viên và giải nội bộ: tư vấn size, thiết kế logo, tên số và duyệt maket trước.',
    primaryCta: 'Gửi yêu cầu cho lớp',
    secondaryCta: 'Xem mẫu học sinh',
    proof: ['Phù hợp đội lớp, khoa, trường', 'Dễ gom size theo danh sách', 'Duyệt tên số trước khi may'],
    pain: 'Lớp thường có nhiều chiều cao, cân nặng và ý kiến thiết kế khác nhau. Nếu không gom thông tin sớm, phần size, tên số và màu áo dễ phải sửa nhiều vòng.',
    outcome: 'Một bộ áo đồng bộ để đi tập, thi đấu, chụp ảnh kỷ yếu thể thao hoặc tham gia giải nội bộ mà vẫn vừa với từng thành viên.',
    useCases: ['Áo đội lớp THCS, THPT', 'Đội tuyển trường', 'Đội khoa, câu lạc bộ sinh viên', 'Giải bóng rổ nội bộ'],
    benefits: [
      { title: 'Dễ gom thông tin', text: 'Có checklist logo, tên số, size và ngày cần nhận để lớp trưởng hoặc ban cán sự chốt nhanh hơn.' },
      { title: 'Thiết kế đúng màu lớp', text: 'Phối màu theo trường, khoa, logo riêng hoặc concept mà cả lớp đã thống nhất.' },
      { title: 'Tư vấn form dễ mặc', text: 'Ưu tiên form vận động thoải mái, phù hợp nhiều vóc dáng học sinh và sinh viên.' },
    ],
    checklist: ['Logo lớp, khoa hoặc trường', 'Tên đội, tên cầu thủ và số áo', 'Danh sách chiều cao, cân nặng hoặc size', 'Ngày cần mặc cho giải hoặc sự kiện', 'Mẫu áo hoặc màu chủ đạo cả lớp thích'],
    steps: [
      { title: 'Gom danh sách', text: 'Chuẩn bị số lượng, size dự kiến, tên số và deadline nhận áo.' },
      { title: 'Chọn hướng áo', text: 'Gửi màu trường, logo lớp hoặc mẫu áo muốn tham khảo.' },
      { title: 'Duyệt maket', text: 'Kiểm tra chính tả tên số, vị trí logo và phối màu trước khi sản xuất.' },
      { title: 'Nhận và phân áo', text: 'Đơn hàng được đóng gói theo thông tin đã chốt để lớp dễ kiểm tra.' },
    ],
    faq: [
      { question: 'Lớp chưa có logo thì bắt đầu thế nào?', answer: 'Có thể bắt đầu bằng tên lớp, màu trường và một mẫu áo tham khảo. Logo hoặc chữ đội có thể trao đổi tiếp trong bước maket.' },
      { question: 'Có hỗ trợ chọn size cho học sinh không?', answer: 'Có. Bạn có thể gửi chiều cao, cân nặng hoặc size dự kiến để được đối chiếu trước khi chốt danh sách.' },
    ],
  },
  {
    slug: 'clb-doi-bong-phong-trao',
    path: '/ao-bong-ro-clb-doi-phong-trao/',
    eyebrow: 'CLB & Đội bóng phong trào',
    title: 'May áo bóng rổ cho câu lạc bộ và đội phong trào',
    shortTitle: 'CLB & Đội phong trào',
    description: 'Dành cho nhóm bạn, câu lạc bộ, trung tâm đào tạo và đội bóng công ty.',
    heroTitle: 'Áo bóng rổ riêng cho đội chơi thường xuyên, nhìn đồng bộ từ sân tập đến trận giao hữu.',
    heroDescription: 'Thiết kế theo màu đội, tên số và logo riêng để nhóm bạn, CLB, trung tâm đào tạo hoặc đội bóng công ty có nhận diện rõ ràng hơn mỗi lần ra sân.',
    metaTitle: 'May Áo Bóng Rổ Cho CLB & Đội Phong Trào',
    metaDescription: 'May áo bóng rổ cho nhóm bạn, câu lạc bộ, trung tâm đào tạo và đội công ty: thiết kế logo, tên số, phối màu đội và tư vấn chất liệu.',
    primaryCta: 'Tư vấn cho CLB',
    secondaryCta: 'Xem mẫu CLB',
    proof: ['Đồng bộ màu và logo đội', 'Phù hợp tập luyện thường xuyên', 'Có thể may bổ sung theo đội'],
    pain: 'Đội phong trào cần áo bền, dễ vận động và vẫn có cá tính riêng. Vấn đề thường nằm ở việc cân bằng ngân sách, chất liệu và thiết kế sao cho cả đội đều muốn mặc.',
    outcome: 'Một bộ áo có nhận diện rõ, đủ thoải mái cho lịch tập đều đặn và đủ nổi bật khi thi đấu giao hữu, giải phong trào hoặc hoạt động công ty.',
    useCases: ['Nhóm bạn chơi cố định', 'Câu lạc bộ bóng rổ', 'Trung tâm đào tạo', 'Đội bóng công ty'],
    benefits: [
      { title: 'Nhận diện đội rõ hơn', text: 'Logo, tên đội, số áo và màu chủ đạo được đưa vào maket để cả đội duyệt trước.' },
      { title: 'Chất liệu theo tần suất chơi', text: 'Tư vấn vải theo nhu cầu tập luyện, thi đấu và ngân sách của đội.' },
      { title: 'Dễ đặt lại khi cần', text: 'Thông tin tên số, màu và maket giúp đội thuận tiện hơn khi cần may bổ sung.' },
    ],
    checklist: ['Logo hoặc tên đội', 'Số lượng bộ hiện tại và dự kiến may thêm', 'Màu chủ đạo, màu phụ', 'Danh sách tên số', 'Chất liệu hoặc ngân sách mong muốn'],
    steps: [
      { title: 'Chọn bản sắc đội', text: 'Xác định màu, logo và phong cách mạnh mẽ, tối giản hoặc nổi bật.' },
      { title: 'Khớp chất liệu', text: 'Chọn vải theo tần suất tập, cảm giác mặc và mức giá phù hợp.' },
      { title: 'Duyệt tên số', text: 'Rà lại danh sách cá nhân hóa để tránh sai sót khi in.' },
      { title: 'Chốt sản xuất', text: 'Xác nhận size, số lượng và thời gian giao trước khi may.' },
    ],
    faq: [
      { question: 'Đội công ty có thể thêm logo doanh nghiệp không?', answer: 'Có. Bạn gửi logo và vị trí mong muốn để đưa vào maket trước khi xác nhận.' },
      { question: 'CLB muốn may thêm sau này có được không?', answer: 'Có thể trao đổi dựa trên mẫu đã chốt. Nên giữ lại mã mẫu, màu và danh sách tên số để đặt bổ sung thuận tiện hơn.' },
    ],
  },
  {
    slug: 'giai-dau-su-kien',
    path: '/ao-bong-ro-giai-dau-su-kien/',
    eyebrow: 'Giải đấu & Sự kiện',
    title: 'May áo bóng rổ cho giải đấu, sự kiện và ban tổ chức',
    shortTitle: 'Giải đấu & Sự kiện',
    description: 'Dành cho ban tổ chức, giải học sinh – sinh viên, giải phong trào và sự kiện bóng rổ.',
    heroTitle: 'Bộ áo giải đấu cần rõ tiến độ, đúng nhận diện và dễ bàn giao cho nhiều đội.',
    heroDescription: 'Hỗ trợ ban tổ chức chuẩn bị áo thi đấu, áo staff hoặc đồng phục sự kiện với danh sách đội, size, logo tài trợ và mốc giao hàng rõ ràng.',
    metaTitle: 'May Áo Bóng Rổ Cho Giải Đấu & Sự Kiện',
    metaDescription: 'Landing page may áo bóng rổ cho ban tổ chức, giải học sinh sinh viên, giải phong trào và sự kiện bóng rổ: tiến độ, size, logo tài trợ, bàn giao.',
    primaryCta: 'Gửi brief giải đấu',
    secondaryCta: 'Xem bảng giá',
    proof: ['Phù hợp nhiều đội cùng lúc', 'Rõ deadline và bàn giao', 'Hỗ trợ logo tài trợ'],
    pain: 'Giải đấu có nhiều đầu việc chạy song song: đội tham gia, lịch thi đấu, truyền thông, tài trợ và thời điểm nhận áo. Nếu file size hoặc logo không rõ, ban tổ chức rất dễ trễ tiến độ.',
    outcome: 'Một phương án áo dễ kiểm soát cho nhiều đội hoặc nhóm staff, giúp ban tổ chức chốt nhận diện, deadline và thông tin bàn giao trước ngày sự kiện.',
    useCases: ['Giải học sinh, sinh viên', 'Giải phong trào', 'Sự kiện bóng rổ cộng đồng', 'Áo staff, trọng tài, ban tổ chức'],
    benefits: [
      { title: 'Quản lý nhiều nhóm rõ ràng', text: 'Tách thông tin theo đội, nhóm staff hoặc nhóm ban tổ chức để hạn chế nhầm size và tên số.' },
      { title: 'Logo tài trợ có vị trí duyệt trước', text: 'Các logo tài trợ, logo giải và thông tin nhận diện được kiểm tra trong maket.' },
      { title: 'Tập trung vào mốc giao hàng', text: 'Brief bắt đầu từ ngày sự kiện để chọn phương án sản xuất phù hợp với tiến độ.' },
    ],
    checklist: ['Ngày tổ chức và ngày cần nhận áo', 'Số đội, số bộ mỗi đội', 'Logo giải và logo tài trợ', 'Danh sách size theo từng nhóm', 'Yêu cầu áo thi đấu, áo staff hoặc cả hai'],
    steps: [
      { title: 'Gửi brief sự kiện', text: 'Cung cấp deadline, số đội, số lượng và yêu cầu nhận diện.' },
      { title: 'Chia nhóm đơn hàng', text: 'Tách thông tin theo đội, staff, trọng tài hoặc ban tổ chức.' },
      { title: 'Duyệt nhận diện', text: 'Kiểm tra logo giải, logo tài trợ, màu và vị trí in trên áo.' },
      { title: 'Bàn giao theo lịch', text: 'Chốt địa chỉ, người nhận và phương án giao trước ngày diễn ra.' },
    ],
    faq: [
      { question: 'Có làm áo cho nhiều đội trong cùng một giải không?', answer: 'Có. Bạn nên gửi bảng số lượng và size theo từng đội để tư vấn phương án rõ ràng hơn.' },
      { question: 'Logo nhà tài trợ cần chuẩn bị file gì?', answer: 'Nên gửi file rõ nét như AI, PDF, SVG hoặc PNG chất lượng cao. Nếu chỉ có ảnh, có thể gửi trước để kiểm tra khả năng dùng trong maket.' },
    ],
  },
  {
    slug: 'doi-tuyen-chuyen-nghiep',
    path: '/ao-bong-ro-doi-tuyen-chuyen-nghiep/',
    eyebrow: 'Đội tuyển & Chuyên nghiệp',
    title: 'May áo bóng rổ cho học viện, đội tuyển và câu lạc bộ chuyên nghiệp',
    shortTitle: 'Đội tuyển & Chuyên nghiệp',
    description: 'Dành cho học viện, đội tuyển, câu lạc bộ bán chuyên và chuyên nghiệp.',
    heroTitle: 'Đồng phục thi đấu cần giữ chuẩn nhận diện, form vận động và chi tiết cá nhân hóa.',
    heroDescription: 'Dành cho học viện, đội tuyển và câu lạc bộ cần bộ áo có hệ nhận diện rõ ràng, chất liệu phù hợp thi đấu và quy trình duyệt kỹ trước sản xuất.',
    metaTitle: 'May Áo Bóng Rổ Cho Đội Tuyển & Chuyên Nghiệp',
    metaDescription: 'May áo bóng rổ cho học viện, đội tuyển, câu lạc bộ bán chuyên và chuyên nghiệp: nhận diện đội, chất liệu thi đấu, tên số, logo và duyệt maket.',
    primaryCta: 'Trao đổi bộ nhận diện',
    secondaryCta: 'Xem chất liệu',
    proof: ['Duyệt kỹ từng chi tiết', 'Phù hợp thi đấu nghiêm túc', 'Đồng bộ nhận diện đội'],
    pain: 'Đội tuyển và học viện thường cần áo có tiêu chuẩn nhận diện chặt hơn: màu, logo, số áo, nhà tài trợ, chất liệu và form mặc phải nhất quán qua nhiều đợt sử dụng.',
    outcome: 'Một bộ đồng phục thể hiện đúng tinh thần đội, ổn định khi thi đấu và đủ rõ ràng để duy trì nhận diện qua mùa giải hoặc chương trình đào tạo.',
    useCases: ['Học viện bóng rổ', 'Đội tuyển trường hoặc tỉnh', 'Câu lạc bộ bán chuyên', 'Câu lạc bộ chuyên nghiệp'],
    benefits: [
      { title: 'Giữ chuẩn nhận diện', text: 'Màu, logo, số áo, tên đội và nhà tài trợ được đưa vào hệ thống maket để duyệt kỹ.' },
      { title: 'Chọn chất liệu theo cường độ', text: 'Tư vấn vải theo nhu cầu tập luyện, thi đấu và hình ảnh chuyên nghiệp của đội.' },
      { title: 'Quy trình chốt rõ', text: 'Các điểm cần xác nhận được gom thành checklist để giảm rủi ro khi sản xuất số lượng lớn.' },
    ],
    checklist: ['Brand guideline hoặc màu nhận diện', 'Logo đội và logo nhà tài trợ', 'Quy định vị trí tên, số, biểu trưng', 'Danh sách size và vai trò thành viên', 'Lịch thi đấu, lịch chụp ảnh hoặc ngày ra mắt áo'],
    steps: [
      { title: 'Rà nhận diện', text: 'Kiểm tra màu, logo, quy chuẩn đặt tên số và tài trợ.' },
      { title: 'Chọn cấu hình áo', text: 'Trao đổi form, chất liệu và mức hoàn thiện theo nhu cầu thi đấu.' },
      { title: 'Duyệt maket chi tiết', text: 'Xác nhận từng vị trí in, tên số và các điểm nhận diện.' },
      { title: 'Sản xuất theo danh sách', text: 'Chốt số lượng, size và lịch bàn giao theo kế hoạch của đội.' },
    ],
    faq: [
      { question: 'Có thể làm theo bộ nhận diện sẵn của đội không?', answer: 'Có. Bạn gửi màu, logo, quy chuẩn hoặc hình tham khảo để đối chiếu trong quá trình lên maket.' },
      { question: 'Đội cần chất liệu thi đấu nên chọn gì?', answer: 'Tùy cảm giác mặc và ngân sách. Bạn có thể xem trang chất liệu hoặc gửi yêu cầu để được tư vấn phương án phù hợp hơn.' },
    ],
  },
  {
    slug: 'hoc-sinh-ha-noi',
    path: '/ao-bong-ro-hoc-sinh-ha-noi/',
    eyebrow: 'Học sinh Hà Nội',
    title: 'May áo bóng rổ học sinh Hà Nội',
    shortTitle: 'Học sinh Hà Nội',
    description: 'Dành cho lớp, đội tuyển trường và câu lạc bộ học sinh tại Hà Nội.',
    heroTitle: 'Áo bóng rổ học sinh Hà Nội dễ gom size, rõ tên số và kịp ngày ra sân.',
    heroDescription: 'Từ đội lớp, đội tuyển trường đến câu lạc bộ sau giờ học, bạn có thể gửi màu trường, logo lớp, danh sách tên số và deadline để được tư vấn phương án áo phù hợp.',
    heroImage: '/images/mayaobongro/landing-20260724/ao-bong-ro-hoc-sinh-ha-noi.webp',
    heroImageAlt: 'Học sinh Hà Nội mặc đồng phục bóng rổ thiết kế riêng trên sân trường',
    metaTitle: 'Áo Bóng Rổ Học Sinh Hà Nội | May Đồng Phục Theo Yêu Cầu',
    metaDescription: 'May áo bóng rổ học sinh Hà Nội cho lớp, đội tuyển trường và CLB: tư vấn size, tên số, màu trường, logo lớp và duyệt maket trước khi may.',
    primaryCta: 'Tư vấn áo học sinh Hà Nội',
    secondaryCta: 'Xem mẫu học sinh',
    proof: ['Phù hợp lớp, trường, CLB học sinh', 'Tư vấn size theo danh sách', 'Duyệt maket tên số trước khi may'],
    pain: 'Một đơn áo học sinh thường có nhiều size, nhiều ý kiến màu sắc và deadline gắn với giải trường hoặc buổi chụp ảnh. Nếu không chốt danh sách sớm, tên số và form áo rất dễ phải sửa nhiều vòng.',
    outcome: 'Một bộ đồng phục bóng rổ gọn gàng cho lớp hoặc đội trường, mặc thoải mái khi tập luyện và đủ đồng bộ khi thi đấu, chụp ảnh hoặc tham gia hoạt động thể thao.',
    useCases: ['Đội bóng rổ lớp tại Hà Nội', 'Đội tuyển trường THCS, THPT', 'Câu lạc bộ bóng rổ học sinh', 'Áo thi đấu cho giải nội bộ'],
    benefits: [
      { title: 'Gom size rõ hơn', text: 'Checklist chiều cao, cân nặng, tên và số áo giúp lớp trưởng hoặc ban cán sự kiểm tra trước khi gửi sản xuất.' },
      { title: 'Giữ đúng màu trường', text: 'Maket có thể bám theo màu trường, logo lớp hoặc concept mà đội đã thống nhất.' },
      { title: 'Hạn chế sai tên số', text: 'Danh sách cá nhân hóa được rà lại trước khi may để giảm lỗi chính tả và nhầm số áo.' },
    ],
    checklist: ['Tên lớp, tên đội hoặc tên trường', 'Logo lớp, logo trường nếu có', 'Danh sách tên, số áo, chiều cao và cân nặng', 'Màu chủ đạo cả đội muốn dùng', 'Ngày cần nhận để đi tập, thi đấu hoặc chụp ảnh'],
    steps: [
      { title: 'Gửi thông tin đội', text: 'Nhắn số lượng, độ tuổi, màu muốn dùng và thời điểm cần nhận áo.' },
      { title: 'Chọn hướng thiết kế', text: 'Đội có thể gửi mẫu thích, logo lớp hoặc để tư vấn phối màu theo tinh thần trường.' },
      { title: 'Duyệt maket', text: 'Kiểm tra tên, số, vị trí logo và phối màu trước khi sản xuất.' },
      { title: 'Chốt bàn giao', text: 'Xác nhận danh sách cuối, địa chỉ nhận và thông tin liên hệ để giao hàng thuận tiện.' },
    ],
    faq: [
      { question: 'Lớp ở Hà Nội đặt từ xa được không?', answer: 'Được. Bạn gửi brief, mẫu thích và danh sách size qua Zalo để được tư vấn và duyệt maket trước khi chốt may.' },
      { question: 'Chưa biết size cho từng bạn thì làm sao?', answer: 'Bạn có thể gửi chiều cao, cân nặng hoặc size áo thường mặc. Đội tư vấn sẽ hỗ trợ đối chiếu trước khi chốt danh sách.' },
    ],
  },
  {
    slug: 'truong-hoc-tphcm',
    path: '/may-ao-bong-ro-truong-hoc-tphcm/',
    eyebrow: 'Trường học TPHCM',
    title: 'May áo bóng rổ trường học TPHCM',
    shortTitle: 'Trường học TPHCM',
    description: 'Dành cho đội trường, lớp, câu lạc bộ và giải học sinh tại TPHCM.',
    heroTitle: 'Đồng phục bóng rổ trường học TPHCM chốt nhanh từ danh sách size đến maket.',
    heroDescription: 'Phù hợp đội tuyển trường, lớp, câu lạc bộ và giải nội bộ cần áo bóng rổ có logo, tên số, màu nhận diện và lịch bàn giao rõ ràng.',
    heroImage: '/images/mayaobongro/landing-20260724/may-ao-bong-ro-truong-hoc-tphcm.webp',
    heroImageAlt: 'Học sinh TPHCM kiểm tra danh sách size và áo bóng rổ trường học',
    metaTitle: 'May Áo Bóng Rổ Trường Học TPHCM | Đồng Phục Theo Yêu Cầu',
    metaDescription: 'May áo bóng rổ trường học TPHCM cho lớp, đội tuyển và CLB: thiết kế logo, tên số, tư vấn size, duyệt maket và bàn giao theo lịch.',
    primaryCta: 'Gửi brief trường học',
    secondaryCta: 'Xem mẫu trường học',
    proof: ['Hợp đội lớp và đội tuyển trường', 'Kiểm soát danh sách size', 'Có maket trước khi sản xuất'],
    pain: 'Các đơn trường học thường cần thống nhất nhanh giữa học sinh, giáo viên phụ trách và ban tổ chức giải. Nếu file logo, màu áo hoặc danh sách size rời rạc, tiến độ rất dễ bị kéo dài.',
    outcome: 'Một phương án áo bóng rổ rõ thông tin cho đội trường hoặc nhiều lớp, giúp người phụ trách dễ duyệt thiết kế, gom size và theo dõi deadline nhận áo.',
    useCases: ['Đội tuyển bóng rổ trường tại TPHCM', 'Áo lớp thi đấu bóng rổ', 'CLB bóng rổ học sinh', 'Giải nội bộ cấp trường'],
    benefits: [
      { title: 'Brief dễ duyệt', text: 'Tách rõ logo, màu, tên số, size và deadline để giáo viên hoặc ban cán sự kiểm tra từng phần.' },
      { title: 'Form hợp học sinh', text: 'Tư vấn form vận động thoải mái, phù hợp nhiều vóc dáng trong cùng một đội.' },
      { title: 'Tiến độ rõ ràng', text: 'Bắt đầu từ ngày cần nhận áo để chọn cách triển khai phù hợp với lịch tập hoặc lịch giải.' },
    ],
    checklist: ['Tên trường, lớp hoặc CLB', 'Logo trường, logo đội hoặc file tài trợ nếu có', 'Số lượng theo từng lớp hoặc từng đội', 'Danh sách size, tên và số áo', 'Ngày cần nhận và khu vực giao hàng'],
    steps: [
      { title: 'Gửi danh sách', text: 'Chuẩn bị số lượng, size, tên số và nhóm nhận áo.' },
      { title: 'Chọn nhận diện', text: 'Chốt màu trường, logo và phong cách áo đội muốn theo.' },
      { title: 'Duyệt chi tiết', text: 'Rà tên, số, logo và vị trí in trên maket.' },
      { title: 'Bàn giao', text: 'Xác nhận thời điểm, địa chỉ và người nhận để đơn hàng được kiểm tra dễ hơn.' },
    ],
    faq: [
      { question: 'Có làm cho nhiều lớp trong cùng một trường không?', answer: 'Có. Bạn nên gửi danh sách tách theo lớp hoặc đội để kiểm soát size, tên số và số lượng từng nhóm.' },
      { question: 'Trường chưa có mẫu áo thì bắt đầu từ đâu?', answer: 'Có thể bắt đầu bằng màu trường, logo và 2-3 mẫu tham khảo. Từ đó đội tư vấn sẽ đề xuất hướng maket dễ duyệt hơn.' },
    ],
  },
  {
    slug: 'hoc-sinh-da-nang',
    path: '/ao-bong-ro-hoc-sinh-da-nang/',
    eyebrow: 'Học sinh Đà Nẵng',
    title: 'May áo bóng rổ học sinh Đà Nẵng',
    shortTitle: 'Học sinh Đà Nẵng',
    description: 'Dành cho lớp, đội trường và nhóm học sinh chơi bóng rổ tại Đà Nẵng.',
    heroTitle: 'Áo bóng rổ học sinh Đà Nẵng sáng màu, dễ mặc và đồng bộ trên sân.',
    heroDescription: 'Dành cho đội lớp, đội trường, nhóm bạn hoặc câu lạc bộ học sinh muốn có bộ áo bóng rổ riêng với màu sắc rõ, tên số chuẩn và form thoải mái khi vận động.',
    heroImage: '/images/mayaobongro/landing-20260724/ao-bong-ro-hoc-sinh-da-nang.webp',
    heroImageAlt: 'Học sinh Đà Nẵng mặc áo bóng rổ thiết kế riêng trên sân ngoài trời',
    metaTitle: 'Áo Bóng Rổ Học Sinh Đà Nẵng | May Đồng Phục Theo Yêu Cầu',
    metaDescription: 'May áo bóng rổ học sinh Đà Nẵng cho lớp, đội trường và CLB: tư vấn màu, form, size, tên số và duyệt maket trước sản xuất.',
    primaryCta: 'Tư vấn áo học sinh Đà Nẵng',
    secondaryCta: 'Xem mẫu học sinh',
    proof: ['Phù hợp lớp và đội trường', 'Dễ chọn màu nổi bật', 'Tư vấn size trước khi chốt'],
    pain: 'Đội học sinh thường muốn áo vừa nổi bật trên sân vừa dễ mặc ngoài giờ tập. Khó nhất là gom đủ size, chọn màu cả nhóm cùng thích và tránh sai tên số khi cá nhân hóa.',
    outcome: 'Một bộ áo bóng rổ có màu sắc tươi, form thoải mái và thông tin cá nhân hóa rõ để cả đội tự tin khi tập luyện, thi đấu hoặc tham gia giải trường.',
    useCases: ['Đội lớp tại Đà Nẵng', 'Nhóm bạn chơi bóng rổ sau giờ học', 'Đội tuyển trường', 'CLB bóng rổ học sinh'],
    benefits: [
      { title: 'Màu áo dễ nhận diện', text: 'Có thể phối màu theo trường, theo nhóm bạn hoặc theo concept sáng, năng động.' },
      { title: 'Size theo vóc dáng', text: 'Dựa trên chiều cao, cân nặng hoặc size thường mặc để tư vấn trước khi chốt.' },
      { title: 'Duyệt trước khi may', text: 'Maket giúp đội kiểm tra logo, tên số và bố cục để hạn chế sửa sau.' },
    ],
    checklist: ['Tên đội hoặc tên lớp', 'Màu chủ đạo và màu phụ', 'Logo hoặc hình tham khảo', 'Danh sách tên, số, size', 'Ngày cần mặc cho tập luyện, giải hoặc chụp ảnh'],
    steps: [
      { title: 'Chọn concept', text: 'Gửi màu và mẫu áo mà đội muốn tham khảo.' },
      { title: 'Gom size', text: 'Tổng hợp chiều cao, cân nặng, tên và số áo.' },
      { title: 'Duyệt maket', text: 'Kiểm tra tổng thể áo trước khi xác nhận sản xuất.' },
      { title: 'Nhận áo', text: 'Chốt thông tin giao hàng và người nhận để đội dễ kiểm tra.' },
    ],
    faq: [
      { question: 'Đội ở Đà Nẵng có cần đến trực tiếp không?', answer: 'Không bắt buộc. Bạn có thể gửi thông tin qua Zalo để trao đổi mẫu, size và maket từ xa.' },
      { question: 'Áo học sinh nên chọn kiểu màu nào?', answer: 'Nên chọn 1 màu chính và 1-2 màu phụ để áo nổi bật nhưng vẫn dễ duyệt trong tập thể.' },
    ],
  },
  {
    slug: 'tre-em',
    path: '/ao-bong-ro-tre-em/',
    eyebrow: 'Trẻ em',
    title: 'Áo bóng rổ trẻ em thiết kế theo yêu cầu',
    shortTitle: 'Trẻ em',
    description: 'Dành cho lớp kỹ năng, trung tâm đào tạo, đội thiếu nhi và nhóm trẻ yêu bóng rổ.',
    heroTitle: 'Áo bóng rổ trẻ em cần nhẹ, dễ vận động và chọn size kỹ hơn.',
    heroDescription: 'Phù hợp lớp kỹ năng, đội thiếu nhi, trung tâm đào tạo hoặc phụ huynh đặt áo cho nhóm trẻ cần form thoải mái, màu vui mắt và thông tin size rõ ràng.',
    heroImage: '/images/mayaobongro/landing-20260724/ao-bong-ro-tre-em.webp',
    heroImageAlt: 'Trẻ em mặc đồng phục bóng rổ trong buổi tập cùng huấn luyện viên',
    metaTitle: 'Áo Bóng Rổ Trẻ Em | May Đồng Phục Theo Size Và Đội Nhóm',
    metaDescription: 'May áo bóng rổ trẻ em cho lớp kỹ năng, trung tâm đào tạo và đội thiếu nhi: tư vấn size theo tuổi, chiều cao, form vận động và thiết kế riêng.',
    primaryCta: 'Tư vấn áo trẻ em',
    secondaryCta: 'Xem vải & size',
    proof: ['Tư vấn theo tuổi và chiều cao', 'Form dễ vận động', 'Màu sắc phù hợp nhóm trẻ'],
    pain: 'Trẻ em thay đổi vóc dáng nhanh, vận động nhiều và cần áo thoải mái hơn áo người lớn thu nhỏ. Nếu chọn size qua loa, áo dễ bị chật vai, dài quá hoặc khó mặc khi tập.',
    outcome: 'Một bộ áo bóng rổ nhẹ, dễ mặc, đủ thoải mái cho trẻ chạy nhảy và đủ đồng bộ cho lớp kỹ năng, trung tâm hoặc đội thiếu nhi.',
    useCases: ['Lớp bóng rổ thiếu nhi', 'Trung tâm đào tạo bóng rổ', 'Đội trẻ của trường', 'Nhóm phụ huynh đặt áo cho con'],
    benefits: [
      { title: 'Chọn size cẩn thận', text: 'Ưu tiên thông tin tuổi, chiều cao, cân nặng và thói quen mặc rộng hay vừa.' },
      { title: 'Form dễ vận động', text: 'Tư vấn kiểu áo giúp trẻ chạy, ném bóng và tập luyện thoải mái hơn.' },
      { title: 'Màu vui nhưng gọn', text: 'Thiết kế có thể tươi sáng, dễ nhận diện mà vẫn sạch sẽ khi lên đồng phục đội.' },
    ],
    checklist: ['Độ tuổi hoặc lớp của trẻ', 'Chiều cao, cân nặng từng bé', 'Số lượng áo hoặc bộ', 'Màu yêu thích của nhóm', 'Tên, số áo và logo trung tâm nếu có'],
    steps: [
      { title: 'Gửi độ tuổi', text: 'Cho biết nhóm trẻ bao nhiêu tuổi, số lượng và thời điểm cần nhận.' },
      { title: 'Tư vấn size', text: 'Đối chiếu chiều cao, cân nặng và form mặc mong muốn.' },
      { title: 'Lên maket', text: 'Duyệt màu, tên số và logo trước khi may.' },
      { title: 'Bàn giao', text: 'Kiểm tra số lượng và thông tin từng bé theo danh sách đã chốt.' },
    ],
    faq: [
      { question: 'Áo trẻ em có nên đặt rộng hơn không?', answer: 'Tùy độ tuổi và cách sử dụng. Với nhóm trẻ đang phát triển nhanh, nên trao đổi chiều cao, cân nặng để chọn form mặc thoải mái nhưng không quá rộng.' },
      { question: 'Có làm cho trung tâm đào tạo bóng rổ không?', answer: 'Có. Bạn có thể gửi logo trung tâm, màu nhận diện và danh sách học viên để lên phương án đồng phục.' },
    ],
  },
  {
    slug: 'thpt',
    path: '/ao-bong-ro-thpt/',
    eyebrow: 'THPT',
    title: 'Áo bóng rổ THPT cho lớp, đội tuyển và giải trường',
    shortTitle: 'THPT',
    description: 'Dành cho học sinh THPT cần áo bóng rổ thi đấu, áo lớp thể thao hoặc đồng phục đội trường.',
    heroTitle: 'Áo bóng rổ THPT phải đủ chất đội, dễ duyệt và đúng deadline giải trường.',
    heroDescription: 'Từ áo lớp thể thao đến đội tuyển trường, đội bạn có thể chốt màu, logo, tên số và form mặc theo danh sách học sinh trước khi đưa vào sản xuất.',
    heroImage: '/images/mayaobongro/landing-20260724/ao-bong-ro-thpt.webp',
    heroImageAlt: 'Đội học sinh THPT mặc áo bóng rổ đen cam chuẩn bị thi đấu trên sân trường',
    metaTitle: 'Áo Bóng Rổ THPT | May Đồng Phục Lớp Và Đội Tuyển Trường',
    metaDescription: 'May áo bóng rổ THPT cho lớp, đội tuyển trường và giải học sinh: thiết kế màu đội, logo, tên số, tư vấn size và duyệt maket.',
    primaryCta: 'Gửi yêu cầu áo THPT',
    secondaryCta: 'Xem bảng giá',
    proof: ['Phù hợp áo lớp và đội trường', 'Dễ duyệt màu, logo, tên số', 'Bám deadline giải học sinh'],
    pain: 'Ở cấp THPT, áo bóng rổ thường vừa là đồng phục thi đấu vừa là dấu ấn của lớp hoặc đội trường. Thử thách là làm sao đủ nổi bật, không rối, đúng size và kịp lịch giải.',
    outcome: 'Một bộ áo bóng rổ có tinh thần riêng của lớp hoặc đội tuyển, mặc thoải mái khi thi đấu và đủ đẹp để lưu lại trong ảnh tập thể.',
    useCases: ['Áo bóng rổ lớp 10, 11, 12', 'Đội tuyển THPT', 'Giải bóng rổ cấp trường', 'Áo thể thao cho kỷ yếu hoặc sự kiện lớp'],
    benefits: [
      { title: 'Thiết kế có cá tính', text: 'Màu, họa tiết, tên đội và số áo có thể đi theo tinh thần lớp hoặc trường.' },
      { title: 'Dễ kiểm danh sách', text: 'Tên, số, size và số lượng được gom rõ để ban cán sự hoặc đội trưởng rà lại.' },
      { title: 'Ưu tiên ngày cần mặc', text: 'Brief luôn tính đến lịch giải, lịch chụp hoặc sự kiện để chọn phương án phù hợp.' },
    ],
    checklist: ['Tên lớp, tên đội hoặc slogan nếu có', 'Logo trường, logo lớp hoặc biểu tượng đội', 'Danh sách tên số và size', 'Mẫu áo tham khảo', 'Ngày cần mặc cho giải hoặc sự kiện'],
    steps: [
      { title: 'Gom ý tưởng', text: 'Tập hợp màu, mẫu tham khảo và tên đội mà cả lớp thống nhất.' },
      { title: 'Rà size', text: 'Gửi chiều cao, cân nặng hoặc size dự kiến để hạn chế lệch form.' },
      { title: 'Duyệt maket', text: 'Kiểm tra chính tả, số áo, logo và bố cục trước khi sản xuất.' },
      { title: 'Nhận theo lịch', text: 'Chốt deadline, địa chỉ và người nhận để cả đội kịp ngày ra sân.' },
    ],
    faq: [
      { question: 'Áo THPT có thể làm theo màu trường không?', answer: 'Có. Bạn gửi màu trường, logo hoặc hình ảnh nhận diện để đưa vào hướng thiết kế.' },
      { question: 'Có cần đủ danh sách tên số ngay từ đầu không?', answer: 'Nên có danh sách sớm để maket và sản xuất ít phải sửa. Nếu chưa đủ, bạn có thể gửi số lượng và size dự kiến trước.' },
    ],
  },
  {
    slug: 'dong-phuc-clb',
    path: '/dong-phuc-clb-bong-ro/',
    eyebrow: 'Đồng phục CLB bóng rổ',
    title: 'Đồng phục CLB bóng rổ thiết kế riêng',
    shortTitle: 'Đồng phục CLB',
    description: 'Dành cho câu lạc bộ, nhóm phong trào, trung tâm đào tạo và đội bóng công ty.',
    heroTitle: 'Đồng phục CLB bóng rổ giúp đội có bản sắc rõ mỗi lần bước vào sân.',
    heroDescription: 'Từ màu đội, logo, tên số đến chất liệu, đội bạn có thể duyệt maket trước để bộ đồng phục vừa dễ mặc khi tập luyện vừa đủ nổi bật khi thi đấu.',
    heroImage: '/images/mayaobongro/landing-20260724/dong-phuc-clb-bong-ro.webp',
    heroImageAlt: 'Câu lạc bộ bóng rổ mặc đồng phục đen đỏ trao đổi chiến thuật trên sân buổi tối',
    metaTitle: 'Đồng Phục CLB Bóng Rổ | May Áo Đội Theo Yêu Cầu',
    metaDescription: 'May đồng phục CLB bóng rổ cho đội phong trào, trung tâm và đội công ty: thiết kế logo, tên số, màu đội, chất liệu và đặt bổ sung.',
    primaryCta: 'Tư vấn đồng phục CLB',
    secondaryCta: 'Xem mẫu CLB',
    proof: ['Đồng bộ màu và logo đội', 'Phù hợp tập luyện thường xuyên', 'Có thông tin để đặt bổ sung'],
    pain: 'CLB cần áo dùng được lâu dài, dễ nhận diện và không bị lẫn với đội khác. Vấn đề thường nằm ở việc cân bằng ngân sách, chất liệu, màu đội và khả năng may thêm khi có thành viên mới.',
    outcome: 'Một bộ đồng phục CLB có nhận diện rõ, thoải mái cho lịch tập đều đặn và đủ chuyên nghiệp khi tham gia giao hữu, giải phong trào hoặc hoạt động truyền thông.',
    useCases: ['CLB bóng rổ phong trào', 'Nhóm bạn chơi cố định', 'Trung tâm đào tạo', 'Đội bóng rổ công ty'],
    benefits: [
      { title: 'Bản sắc đội rõ', text: 'Logo, màu chủ đạo, số áo và tên đội được đưa vào maket để cả CLB duyệt trước.' },
      { title: 'Chất liệu theo tần suất', text: 'Đội tập nhiều, thi đấu nhiều hoặc chỉ cần áo sự kiện sẽ được tư vấn hướng vải khác nhau.' },
      { title: 'Dễ may bổ sung', text: 'Giữ thông tin mẫu, màu và tên số giúp CLB thuận tiện hơn khi có thành viên mới.' },
    ],
    checklist: ['Logo hoặc tên CLB', 'Màu chủ đạo và màu phụ', 'Số lượng hiện tại và dự kiến may thêm', 'Danh sách tên số và size', 'Ngân sách hoặc chất liệu mong muốn'],
    steps: [
      { title: 'Xác định nhận diện', text: 'Chốt màu, logo, tên đội và phong cách áo.' },
      { title: 'Chọn chất liệu', text: 'Tư vấn vải theo lịch tập, cảm giác mặc và ngân sách.' },
      { title: 'Duyệt danh sách', text: 'Rà tên, số, size và số lượng từng thành viên.' },
      { title: 'Chốt sản xuất', text: 'Xác nhận maket, thời gian và phương án bàn giao.' },
    ],
    faq: [
      { question: 'CLB có thể đặt thêm sau khi có thành viên mới không?', answer: 'Có thể trao đổi dựa trên mẫu đã chốt. Nên lưu lại mã mẫu, màu, size và danh sách tên số để đặt bổ sung thuận tiện hơn.' },
      { question: 'Đồng phục CLB nên ưu tiên chất liệu hay thiết kế?', answer: 'Nên cân bằng cả hai. Nếu đội tập thường xuyên, cảm giác mặc và độ thoáng cần được ưu tiên cùng với nhận diện màu/logo.' },
    ],
  },
] as const satisfies BasketballAudience[]

export function getBasketballAudience(slug: string) {
  return BASKETBALL_AUDIENCES.find((audience) => audience.slug === slug)
}
