import type { Metadata } from 'next'
import { ArrowRight } from 'lucide-react'
import Link from 'next/link'

import { Breadcrumbs, ProductGrid, QuoteBand, SectionHeading } from '../components'
import { previewBase as defaultPreviewBase, products } from '../data'
import styles from '../pnd.module.css'

export const metadata: Metadata = { title: 'Thiết kế áo bóng đá đội nhóm', description: 'Tham khảo quy trình chọn mẫu và gửi yêu cầu thiết kế áo bóng đá cho đội nhóm.' }

export default function SeoLandingPage({ base: previewBase = defaultPreviewBase }: { base?: string } = {}) {
  return <><Breadcrumbs base={previewBase} items={[{ label: 'Bóng đá', href: `${previewBase}/danh-muc/bong-da` }, { label: 'Thiết kế áo bóng đá đội nhóm' }]} /><section className={styles.seoHero}><div><span className={styles.eyebrow}>Landing page bổ trợ danh mục</span><h1>Thiết kế áo bóng đá cho đội nhóm</h1><p>Một trang hướng dẫn theo ý định tìm kiếm cụ thể: giúp đội bóng biết cách bắt đầu, xem đúng mẫu liên quan và chuyển sang bước gửi yêu cầu báo giá.</p><div className={styles.heroActions}><Link href={`${previewBase}/danh-muc/bong-da`}>Xem mẫu áo bóng đá <ArrowRight size={17} /></Link></div></div><aside className={styles.seoHeroCard}><h2>Chuẩn bị trong 5 phút</h2><p>Môn và nhóm sử dụng, số lượng dự kiến, màu đội, logo, tên số và mốc thời gian cần áo.</p><a href="https://zalo.me/0989353247" target="_blank" rel="noreferrer">Gửi thông tin qua Zalo</a></aside></section><div className={styles.seoBody}><section><SectionHeading eyebrow="Mẫu phù hợp" title="Điểm bắt đầu cho thiết kế của đội" note="Liên kết trực tiếp về sản phẩm và danh mục thay vì tạo một trang nội dung đứng riêng lẻ." /><ProductGrid items={products.slice(0,4)} base={previewBase} /></section><section className={styles.seoColumns}><article className={styles.seoPanel}><h2>Thiết kế theo bối cảnh sử dụng</h2><p>Đội đá giải phong trào, câu lạc bộ tập định kỳ, lớp học và doanh nghiệp có yêu cầu nhận diện khác nhau. Thông tin bối cảnh giúp tư vấn tập trung vào mẫu và cách bố trí phù hợp.</p><h3>Màu sắc và nhận diện</h3><p>Chọn một màu chính, một màu phụ và độ tương phản đủ rõ cho tên số. Logo nên được gửi ở định dạng rõ nhất hiện có để kiểm tra trước khi hoàn thiện phương án.</p><h3>Giá hiển thị và báo giá</h3><p>Mỗi sản phẩm có giá thấp nhất để khách hàng sàng lọc ban đầu. Cấu hình cuối cùng được báo giá sau khi xác nhận số lượng và yêu cầu tùy chỉnh.</p></article><aside className={`${styles.seoPanel} ${styles.faq}`}><h2>Câu hỏi thường gặp</h2><details open><summary>Có thể đổi màu từ mẫu có sẵn không?</summary><p>Có thể gửi màu đội và logo để bộ phận tư vấn kiểm tra phạm vi điều chỉnh trên mẫu đã chọn.</p></details><details><summary>Cần chuẩn bị gì để nhận báo giá?</summary><p>Số lượng, mẫu quan tâm, nội dung tùy chỉnh và thời gian dự kiến là các thông tin nên có.</p></details><details><summary>Giá trên sản phẩm có phải giá cuối cùng?</summary><p>Không. Đây là giá thấp nhất; báo giá cuối cùng phụ thuộc cấu hình thực tế được xác nhận.</p></details></aside></section><nav className={styles.miniLinks} aria-label="Nội dung liên quan"><Link href={`${previewBase}/danh-muc/bong-da`}><span>Danh mục</span>Kho mẫu áo bóng đá</Link><Link href={`${previewBase}/blog/cach-chon-ao-the-thao-cho-doi-nhom`}><span>Hướng dẫn</span>Cách chọn áo cho đội</Link><Link href={`${previewBase}/blog/chuan-bi-file-logo-in-ao`}><span>Nhận diện</span>Chuẩn bị file logo</Link></nav><QuoteBand compact /></div></>
}
