/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    'tenant-pinterest-connections': TenantPinterestConnection;
    'catalog-distributions': CatalogDistribution;
    'category-distributions': CategoryDistribution;
    'catalog-taxonomies': CatalogTaxonomy;
    'catalog-views': CatalogView;
    'navigation-menus': NavigationMenu;
    'navigation-items': NavigationItem;
    media: Media;
    'migration-runs': MigrationRun;
    'product-categories': ProductCategory;
    products: Product;
    pages: Page;
    posts: Post;
    'web-content': WebContent;
    'store-settings': StoreSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      outboundDistributions: 'catalog-distributions';
      inboundDistributions: 'catalog-distributions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-pinterest-connections': TenantPinterestConnectionsSelect<false> | TenantPinterestConnectionsSelect<true>;
    'catalog-distributions': CatalogDistributionsSelect<false> | CatalogDistributionsSelect<true>;
    'category-distributions': CategoryDistributionsSelect<false> | CategoryDistributionsSelect<true>;
    'catalog-taxonomies': CatalogTaxonomiesSelect<false> | CatalogTaxonomiesSelect<true>;
    'catalog-views': CatalogViewsSelect<false> | CatalogViewsSelect<true>;
    'navigation-menus': NavigationMenusSelect<false> | NavigationMenusSelect<true>;
    'navigation-items': NavigationItemsSelect<false> | NavigationItemsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'migration-runs': MigrationRunsSelect<false> | MigrationRunsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'web-content': WebContentSelect<false> | WebContentSelect<true>;
    'store-settings': StoreSettingsSelect<false> | StoreSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super_admin' | 'tenant_admin' | 'editor';
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  domains: {
    domain: string;
    id?: string | null;
  }[];
  brand: {
    headline: string;
    subheadline: string;
    primaryColor?: string | null;
    accentColor?: string | null;
    style?: ('flevo-inspired' | 'arenix-inspired') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-pinterest-connections".
 */
export interface TenantPinterestConnection {
  id: number;
  tenant?: (number | null) | Tenant;
  tenantConnectionKey?: string | null;
  /**
   * ID tài khoản Pinterest được trả về sau khi OAuth thành công.
   */
  pinterestAccountId?: string | null;
  /**
   * Username tài khoản Pinterest hiện đang liên kết với website này.
   */
  pinterestUsername?: string | null;
  /**
   * Board mặc định để đăng sản phẩm. Nếu bỏ trống, hệ thống sẽ tự tạo board khi đăng lần đầu.
   */
  defaultBoardId?: string | null;
  /**
   * Tên board đang dùng để đăng sản phẩm.
   */
  defaultBoardName?: string | null;
  /**
   * Board sandbox mặc định để quay video hoặc test UI.
   */
  sandboxDefaultBoardId?: string | null;
  /**
   * Tên board sandbox đang dùng để đăng sản phẩm.
   */
  sandboxDefaultBoardName?: string | null;
  /**
   * Danh sách scope OAuth đã cấp cho website này.
   */
  scope?: string | null;
  /**
   * Danh sách scope OAuth sandbox đã cấp cho website này.
   */
  sandboxScope?: string | null;
  accessToken?: string | null;
  sandboxAccessToken?: string | null;
  refreshToken?: string | null;
  sandboxRefreshToken?: string | null;
  tokenExpiresAt?: string | null;
  sandboxTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  sandboxRefreshTokenExpiresAt?: string | null;
  lastPublishedPinId?: string | null;
  lastPublishedProductId?: string | null;
  lastPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-distributions".
 */
export interface CatalogDistribution {
  id: number;
  distributionKey: string;
  sourceTenant: number | Tenant;
  targetTenant: number | Tenant;
  sourceTenantLabel?: string | null;
  targetTenantLabel?: string | null;
  sourceProduct: number | Product;
  targetProduct?: (number | null) | Product;
  status: 'ready' | 'draft_created' | 'published' | 'needs_review' | 'blocked' | 'archived';
  copyMode: 'auto' | 'manual_locked';
  sourceFactFingerprint?: string | null;
  targetCopyFingerprint?: string | null;
  syncedAt?: string | null;
  lastError?: string | null;
  reviewNote?: string | null;
  proposedCopy?: {
    name?: string | null;
    shortDescription?: string | null;
    description?: string | null;
    seoTitle?: string | null;
    metaDescription?: string | null;
    model?: string | null;
    promptVersion?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Đường dẫn sản phẩm, nên giữ ngắn gọn và ổn định.
   */
  slug: string;
  tenantSlugKey?: string | null;
  sku?: string | null;
  sport: 'badminton' | 'volleyball' | 'football' | 'basketball' | 'running' | 'pickleball' | 'other';
  productType?: ('simple' | 'variable' | 'grouped' | 'external') | null;
  publicationStatus?: ('publish' | 'draft' | 'private' | 'pending') | null;
  featured?: boolean | null;
  /**
   * Tổng lượt xem hợp lệ của sản phẩm; mỗi phiên chỉ được tính một lần.
   */
  viewCount?: number | null;
  /**
   * Chọn danh mục hiển thị trên website.
   */
  categories?: (number | ProductCategory)[] | null;
  price?: number | null;
  regularPrice?: number | null;
  salePrice?: number | null;
  compareAtPrice?: number | null;
  currency?: string | null;
  stockStatus?: ('instock' | 'outofstock' | 'onbackorder') | null;
  isPurchasable?: boolean | null;
  isOnBackorder?: boolean | null;
  /**
   * Tóm tắt ngắn hiển thị ở thẻ sản phẩm hoặc đầu trang.
   */
  shortDescription?: string | null;
  /**
   * Nội dung biên tập chính bằng Lexical Rich Text.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  attributes?:
    | {
        name: string;
        values?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  badges?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Từ khóa nội bộ như màu sắc, chất liệu, môn thể thao, dáng áo.
   */
  searchTags?:
    | {
        /**
         * Khóa exact-match chuẩn, ví dụ color.red.
         */
        key?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ảnh sản phẩm đang dùng trên frontend mới.
   */
  gallery?: (number | Media)[] | null;
  legacyImages?:
    | {
        url: string;
        alt?: string | null;
        width?: number | null;
        height?: number | null;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  metaDescription?: string | null;
  canonicalOverride?: string | null;
  /**
   * Đường dẫn canonical gốc của website cũ.
   */
  legacyPath?: string | null;
  tenantLegacyPathKey?: string | null;
  pinterestPublishEnvironment?: ('production' | 'sandbox') | null;
  pinterestPublishedAt?: string | null;
  pinterestBoardName?: string | null;
  pinterestPinId?: string | null;
  pinterestBoardId?: string | null;
  pinterestPinUrl?: string | null;
  /**
   * HTML gốc đã sanitize từ WordPress. Dùng để đối chiếu/migration, không phải nội dung biên tập chính.
   */
  contentHtml?: string | null;
  sourceTags?:
    | {
        name: string;
        slug: string;
        id?: string | null;
      }[]
    | null;
  sourceSystem?: string | null;
  sourceId?: string | null;
  tenantSourceKey?: string | null;
  sourceModifiedAt?: string | null;
  sourceCreatedAt?: string | null;
  sourceChecksum?: string | null;
  outboundDistributionSummary?: string | null;
  inboundDistributionSummary?: string | null;
  outboundDistributions?: {
    docs?: (number | CatalogDistribution)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  inboundDistributions?: {
    docs?: (number | CatalogDistribution)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  slug: string;
  tenantSlugKey?: string | null;
  /**
   * Taxonomy chuẩn dùng để đồng bộ danh mục giữa các website.
   */
  taxonomy?: (number | null) | CatalogTaxonomy;
  /**
   * Danh mục cha trong cây phân loại của website.
   */
  parent?: (number | null) | ProductCategory;
  group: 'sport' | 'type' | 'collection' | 'audience' | 'color' | 'tag';
  description?: string | null;
  navigationLabel?: string | null;
  showInNavigation?: boolean | null;
  navigationOrder?: number | null;
  status?: ('active' | 'hidden' | 'retired') | null;
  legacyPath?: string | null;
  tenantLegacyPathKey?: string | null;
  sourceSystem?: string | null;
  sourceId?: string | null;
  tenantSourceKey?: string | null;
  sourceChecksum?: string | null;
  productCount?: number | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-taxonomies".
 */
export interface CatalogTaxonomy {
  id: number;
  /**
   * Khóa ổn định toàn hệ thống, ví dụ sport.football hoặc color.red.
   */
  key: string;
  name: string;
  kind: 'sport' | 'category' | 'product_type' | 'audience' | 'color' | 'collection' | 'material' | 'fit' | 'tag';
  /**
   * Taxonomy cha, nếu đây là một nhánh con.
   */
  parent?: (number | null) | CatalogTaxonomy;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'retired';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  sourceSystem?: string | null;
  sourceId?: string | null;
  sourceUrl?: string | null;
  sourceChecksum?: string | null;
  tenantSourceKey?: string | null;
  /**
   * Website khác được phép dùng chung media record và cùng file R2. Chỉ quản trị hệ thống được thay đổi.
   */
  sharedWithTenants?: (number | Tenant)[] | null;
  alt: string;
  /**
   * Internal search helpers for tone, gradient, pose, and sport.
   */
  searchTags?:
    | {
        /**
         * Khóa exact-match chuẩn, ví dụ color.red.
         */
        key?: string | null;
        value: string;
        id?: string | null;
      }[]
    | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-distributions".
 */
export interface CategoryDistribution {
  id: number;
  distributionKey: string;
  sourceTenant: number | Tenant;
  targetTenant: number | Tenant;
  sourceTenantLabel?: string | null;
  targetTenantLabel?: string | null;
  sourceKind: 'category' | 'catalog_view';
  sourceCategory?: (number | null) | ProductCategory;
  sourceCatalogView?: (number | null) | CatalogView;
  targetCategory?: (number | null) | ProductCategory;
  targetCatalogView?: (number | null) | CatalogView;
  status: 'ready' | 'draft_created' | 'published' | 'needs_review' | 'blocked' | 'archived';
  copyMode: 'auto' | 'manual_locked';
  sourceFactFingerprint?: string | null;
  targetCopyFingerprint?: string | null;
  syncedAt?: string | null;
  lastError?: string | null;
  reviewNote?: string | null;
  proposedCopy?: {
    name?: string | null;
    navigationLabel?: string | null;
    path?: string | null;
    navigationOrder?: number | null;
    description?: string | null;
    seoTitle?: string | null;
    metaDescription?: string | null;
    model?: string | null;
    promptVersion?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-views".
 */
export interface CatalogView {
  id: number;
  tenant?: (number | null) | Tenant;
  key: string;
  tenantViewKey?: string | null;
  path: string;
  title: string;
  heading: string;
  description?: string | null;
  /**
   * Các taxonomy chuẩn mô tả landing này.
   */
  taxonomy?: (number | CatalogTaxonomy)[] | null;
  /**
   * Bộ lọc exact-match. Chỉ dùng stable key, không dùng contains trên nhãn tiếng Việt.
   */
  filters?: {
    sportKey?: string | null;
    categoryKeys?:
      | {
          key: string;
          id?: string | null;
        }[]
      | null;
    searchTagKeys?:
      | {
          key: string;
          id?: string | null;
        }[]
      | null;
    productTypeKeys?:
      | {
          key: string;
          id?: string | null;
        }[]
      | null;
    audienceKeys?:
      | {
          key: string;
          id?: string | null;
        }[]
      | null;
    colorKeys?:
      | {
          key: string;
          id?: string | null;
        }[]
      | null;
  };
  matchMode: 'all' | 'any';
  indexPolicy: 'indexable' | 'noindex';
  canonicalPath?: string | null;
  includeInSitemap?: boolean | null;
  enabled?: boolean | null;
  /**
   * Ý định phân phối; category-distributions là ledger thực thi.
   */
  distribution?: {
    targetMasters?: (number | Tenant)[] | null;
    navigationLabelOverride?: string | null;
    navigationOrderOverride?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus".
 */
export interface NavigationMenu {
  id: number;
  tenant?: (number | null) | Tenant;
  key: string;
  location: 'header' | 'mobile' | 'footer' | 'contextual';
  tenantMenuKey?: string | null;
  status: 'draft' | 'ready' | 'published' | 'archived';
  revision?: number | null;
  manifestHash?: string | null;
  lastValidatedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-items".
 */
export interface NavigationItem {
  id: number;
  tenant?: (number | null) | Tenant;
  menu: number | NavigationMenu;
  key: string;
  tenantMenuItemKey?: string | null;
  /**
   * Tối đa ba cấp; parent phải cùng menu và cùng website.
   */
  parent?: (number | null) | NavigationItem;
  order?: number | null;
  enabled?: boolean | null;
  label: string;
  description?: string | null;
  iconKey?: string | null;
  featured?: boolean | null;
  targetType: 'group' | 'category' | 'catalogView' | 'page' | 'customUrl';
  targetCategory?: (number | null) | ProductCategory;
  targetCatalogView?: (number | null) | CatalogView;
  targetPage?: (number | null) | Page;
  /**
   * Chỉ path nội bộ, http, https, mailto, tel hoặc anchor.
   */
  customUrl?: string | null;
  childrenSource: 'static' | 'category_query' | 'catalog_view_query';
  categoryQuery?: {
    group?: ('sport' | 'type' | 'collection' | 'audience' | 'color' | 'tag') | null;
    taxonomyRoot?: (number | null) | CatalogTaxonomy;
    minimumProductCount?: number | null;
    sort?: ('navigation_order' | 'name_asc' | 'year_desc' | 'product_count_desc') | null;
    limit?: number | null;
  };
  catalogViewQuery?: {
    taxonomyRoot?: (number | null) | CatalogTaxonomy;
    indexPolicy?: ('indexable' | 'noindex') | null;
    sort?: ('title_asc' | 'updated_desc') | null;
    limit?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  heroTitle: string;
  heroText: string;
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-runs".
 */
export interface MigrationRun {
  id: number;
  tenant?: (number | null) | Tenant;
  runId: string;
  tenantRunKey?: string | null;
  mode: 'snapshot' | 'dry-run' | 'import' | 'delta';
  status: 'running' | 'completed' | 'failed' | 'rolled-back';
  sourceUrl: string;
  snapshotChecksum?: string | null;
  startedAt: string;
  finishedAt?: string | null;
  counts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errors?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-content".
 */
export interface WebContent {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  slug: string;
  tenantSlugKey?: string | null;
  kind: 'page' | 'post';
  legacyPath: string;
  tenantLegacyPathKey?: string | null;
  contentHtml?: string | null;
  excerpt?: string | null;
  publicationStatus?: ('publish' | 'draft' | 'private' | 'pending') | null;
  sourceSystem?: string | null;
  sourceId?: string | null;
  tenantSourceKey?: string | null;
  sourceModifiedAt?: string | null;
  sourceChecksum?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  siteName: string;
  contactPhone?: string | null;
  zaloUrl?: string | null;
  facebookUrl?: string | null;
  tiktokUrl?: string | null;
  instagramUrl?: string | null;
  pinterestUrl?: string | null;
  threadsUrl?: string | null;
  /**
   * Telegram chat ID nhận thông báo từ form tư vấn trên trang chi tiết sản phẩm. Để trống để ẩn form.
   */
  telegramChatId?: string | null;
  /**
   * Địa chỉ cửa hàng/xưởng và link Google Maps dùng cho nút Chỉ đường trên website.
   */
  mapLocations?:
    | {
        label: string;
        address: string;
        googleMapUrl: string;
        id?: string | null;
      }[]
    | null;
  analytics?: {
    /**
     * Bật nhúng Google Analytics 4 trên frontend nếu tenant có Measurement ID.
     */
    ga4Enabled?: boolean | null;
    /**
     * Measurement ID dạng G-XXXXXXX để frontend nhúng Google tag.
     */
    gaMeasurementId?: string | null;
    /**
     * GA4 Property ID dùng cho báo cáo Telegram hằng ngày từ Data API.
     */
    gaPropertyId?: string | null;
    /**
     * Nếu bật và có GA4 Property ID, tenant sẽ được đưa vào báo cáo 23:00 hằng ngày.
     */
    dailyTelegramReportEnabled?: boolean | null;
    /**
     * Bật nhúng Meta Pixel trên frontend nếu tenant có Pixel ID.
     */
    metaPixelEnabled?: boolean | null;
    /**
     * Meta Pixel ID dạng số để frontend ghi nhận PageView.
     */
    metaPixelId?: string | null;
    /**
     * Thêm mã HTML/JS như Google Tag, Meta Pixel, TikTok Pixel hoặc thẻ xác minh. Chỉ quản trị viên đáng tin cậy nên chỉnh mục này.
     */
    customScripts?:
      | {
          /**
           * Tên nội bộ để nhận biết đoạn mã, ví dụ: Google Tag, Meta Pixel, TikTok Pixel.
           */
          label: string;
          enabled?: boolean | null;
          /**
           * Chọn đúng vị trí theo hướng dẫn của nền tảng cung cấp mã.
           */
          position: 'head' | 'bodyStart' | 'bodyEnd';
          /**
           * Dán nguyên đoạn mã HTML/JS do nền tảng cung cấp.
           */
          code: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Giữ legacy cho tới khi menu CMS đã qua shadow diff và được duyệt cutover.
   */
  navigationMode?: ('legacy' | 'cms') | null;
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-pinterest-connections';
        value: number | TenantPinterestConnection;
      } | null)
    | ({
        relationTo: 'catalog-distributions';
        value: number | CatalogDistribution;
      } | null)
    | ({
        relationTo: 'category-distributions';
        value: number | CategoryDistribution;
      } | null)
    | ({
        relationTo: 'catalog-taxonomies';
        value: number | CatalogTaxonomy;
      } | null)
    | ({
        relationTo: 'catalog-views';
        value: number | CatalogView;
      } | null)
    | ({
        relationTo: 'navigation-menus';
        value: number | NavigationMenu;
      } | null)
    | ({
        relationTo: 'navigation-items';
        value: number | NavigationItem;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'migration-runs';
        value: number | MigrationRun;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'web-content';
        value: number | WebContent;
      } | null)
    | ({
        relationTo: 'store-settings';
        value: number | StoreSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  brand?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        primaryColor?: T;
        accentColor?: T;
        style?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-pinterest-connections_select".
 */
export interface TenantPinterestConnectionsSelect<T extends boolean = true> {
  tenant?: T;
  tenantConnectionKey?: T;
  pinterestAccountId?: T;
  pinterestUsername?: T;
  defaultBoardId?: T;
  defaultBoardName?: T;
  sandboxDefaultBoardId?: T;
  sandboxDefaultBoardName?: T;
  scope?: T;
  sandboxScope?: T;
  accessToken?: T;
  sandboxAccessToken?: T;
  refreshToken?: T;
  sandboxRefreshToken?: T;
  tokenExpiresAt?: T;
  sandboxTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  sandboxRefreshTokenExpiresAt?: T;
  lastPublishedPinId?: T;
  lastPublishedProductId?: T;
  lastPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-distributions_select".
 */
export interface CatalogDistributionsSelect<T extends boolean = true> {
  distributionKey?: T;
  sourceTenant?: T;
  targetTenant?: T;
  sourceTenantLabel?: T;
  targetTenantLabel?: T;
  sourceProduct?: T;
  targetProduct?: T;
  status?: T;
  copyMode?: T;
  sourceFactFingerprint?: T;
  targetCopyFingerprint?: T;
  syncedAt?: T;
  lastError?: T;
  reviewNote?: T;
  proposedCopy?:
    | T
    | {
        name?: T;
        shortDescription?: T;
        description?: T;
        seoTitle?: T;
        metaDescription?: T;
        model?: T;
        promptVersion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category-distributions_select".
 */
export interface CategoryDistributionsSelect<T extends boolean = true> {
  distributionKey?: T;
  sourceTenant?: T;
  targetTenant?: T;
  sourceTenantLabel?: T;
  targetTenantLabel?: T;
  sourceKind?: T;
  sourceCategory?: T;
  sourceCatalogView?: T;
  targetCategory?: T;
  targetCatalogView?: T;
  status?: T;
  copyMode?: T;
  sourceFactFingerprint?: T;
  targetCopyFingerprint?: T;
  syncedAt?: T;
  lastError?: T;
  reviewNote?: T;
  proposedCopy?:
    | T
    | {
        name?: T;
        navigationLabel?: T;
        path?: T;
        navigationOrder?: T;
        description?: T;
        seoTitle?: T;
        metaDescription?: T;
        model?: T;
        promptVersion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-taxonomies_select".
 */
export interface CatalogTaxonomiesSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  kind?: T;
  parent?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-views_select".
 */
export interface CatalogViewsSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  tenantViewKey?: T;
  path?: T;
  title?: T;
  heading?: T;
  description?: T;
  taxonomy?: T;
  filters?:
    | T
    | {
        sportKey?: T;
        categoryKeys?:
          | T
          | {
              key?: T;
              id?: T;
            };
        searchTagKeys?:
          | T
          | {
              key?: T;
              id?: T;
            };
        productTypeKeys?:
          | T
          | {
              key?: T;
              id?: T;
            };
        audienceKeys?:
          | T
          | {
              key?: T;
              id?: T;
            };
        colorKeys?:
          | T
          | {
              key?: T;
              id?: T;
            };
      };
  matchMode?: T;
  indexPolicy?: T;
  canonicalPath?: T;
  includeInSitemap?: T;
  enabled?: T;
  distribution?:
    | T
    | {
        targetMasters?: T;
        navigationLabelOverride?: T;
        navigationOrderOverride?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-menus_select".
 */
export interface NavigationMenusSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  location?: T;
  tenantMenuKey?: T;
  status?: T;
  revision?: T;
  manifestHash?: T;
  lastValidatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-items_select".
 */
export interface NavigationItemsSelect<T extends boolean = true> {
  tenant?: T;
  menu?: T;
  key?: T;
  tenantMenuItemKey?: T;
  parent?: T;
  order?: T;
  enabled?: T;
  label?: T;
  description?: T;
  iconKey?: T;
  featured?: T;
  targetType?: T;
  targetCategory?: T;
  targetCatalogView?: T;
  targetPage?: T;
  customUrl?: T;
  childrenSource?: T;
  categoryQuery?:
    | T
    | {
        group?: T;
        taxonomyRoot?: T;
        minimumProductCount?: T;
        sort?: T;
        limit?: T;
      };
  catalogViewQuery?:
    | T
    | {
        taxonomyRoot?: T;
        indexPolicy?: T;
        sort?: T;
        limit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  sourceSystem?: T;
  sourceId?: T;
  sourceUrl?: T;
  sourceChecksum?: T;
  tenantSourceKey?: T;
  sharedWithTenants?: T;
  alt?: T;
  searchTags?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "migration-runs_select".
 */
export interface MigrationRunsSelect<T extends boolean = true> {
  tenant?: T;
  runId?: T;
  tenantRunKey?: T;
  mode?: T;
  status?: T;
  sourceUrl?: T;
  snapshotChecksum?: T;
  startedAt?: T;
  finishedAt?: T;
  counts?: T;
  errors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  tenantSlugKey?: T;
  taxonomy?: T;
  parent?: T;
  group?: T;
  description?: T;
  navigationLabel?: T;
  showInNavigation?: T;
  navigationOrder?: T;
  status?: T;
  legacyPath?: T;
  tenantLegacyPathKey?: T;
  sourceSystem?: T;
  sourceId?: T;
  tenantSourceKey?: T;
  sourceChecksum?: T;
  productCount?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  tenantSlugKey?: T;
  sku?: T;
  sport?: T;
  productType?: T;
  publicationStatus?: T;
  featured?: T;
  viewCount?: T;
  categories?: T;
  price?: T;
  regularPrice?: T;
  salePrice?: T;
  compareAtPrice?: T;
  currency?: T;
  stockStatus?: T;
  isPurchasable?: T;
  isOnBackorder?: T;
  shortDescription?: T;
  description?: T;
  attributes?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  badges?:
    | T
    | {
        label?: T;
        id?: T;
      };
  searchTags?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  gallery?: T;
  legacyImages?:
    | T
    | {
        url?: T;
        alt?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  seoTitle?: T;
  metaDescription?: T;
  canonicalOverride?: T;
  legacyPath?: T;
  tenantLegacyPathKey?: T;
  pinterestPublishEnvironment?: T;
  pinterestPublishedAt?: T;
  pinterestBoardName?: T;
  pinterestPinId?: T;
  pinterestBoardId?: T;
  pinterestPinUrl?: T;
  contentHtml?: T;
  sourceTags?:
    | T
    | {
        name?: T;
        slug?: T;
        id?: T;
      };
  sourceSystem?: T;
  sourceId?: T;
  tenantSourceKey?: T;
  sourceModifiedAt?: T;
  sourceCreatedAt?: T;
  sourceChecksum?: T;
  outboundDistributionSummary?: T;
  inboundDistributionSummary?: T;
  outboundDistributions?: T;
  inboundDistributions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  heroTitle?: T;
  heroText?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-content_select".
 */
export interface WebContentSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  tenantSlugKey?: T;
  kind?: T;
  legacyPath?: T;
  tenantLegacyPathKey?: T;
  contentHtml?: T;
  excerpt?: T;
  publicationStatus?: T;
  sourceSystem?: T;
  sourceId?: T;
  tenantSourceKey?: T;
  sourceModifiedAt?: T;
  sourceChecksum?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  tenant?: T;
  siteName?: T;
  contactPhone?: T;
  zaloUrl?: T;
  facebookUrl?: T;
  tiktokUrl?: T;
  instagramUrl?: T;
  pinterestUrl?: T;
  threadsUrl?: T;
  telegramChatId?: T;
  mapLocations?:
    | T
    | {
        label?: T;
        address?: T;
        googleMapUrl?: T;
        id?: T;
      };
  analytics?:
    | T
    | {
        ga4Enabled?: T;
        gaMeasurementId?: T;
        gaPropertyId?: T;
        dailyTelegramReportEnabled?: T;
        metaPixelEnabled?: T;
        metaPixelId?: T;
        customScripts?:
          | T
          | {
              label?: T;
              enabled?: T;
              position?: T;
              code?: T;
              id?: T;
            };
      };
  navigationMode?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}