server {
    listen 80;
    server_name mayaobongda.vn www.mayaobongda.vn;
    client_max_body_size 32M;

    access_log /var/log/nginx/mayaobongda.vn_access.log;
    error_log /var/log/nginx/mayaobongda.vn_error.log;

    if ($host = www.mayaobongda.vn) {
        return 301 https://mayaobongda.vn$request_uri;
    }

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    location / {
        proxy_pass http://10.10.0.58;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

        proxy_buffering on;
        proxy_buffers 16 32k;
        proxy_buffer_size 64k;
    }
}
